apiVersion: v1
kind: Service
metadata:
  name: go-web-app-svc
  namespace: go-app
spec:
  selector:
    app: go-web-app
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080